import argparse

from example_spacecontrol import main


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run TRELLIS.2 sparse guidance on a shoe-last control mesh")
    parser.add_argument("--image", type=str, required=True, help="Path to the input image")
    parser.add_argument("--control", type=str, required=True, help="Path to the spatial control mesh")
    parser.add_argument("--tau", type=int, default=6, help="SpaceControl tau when control_mode is both")
    parser.add_argument("--out_dir", type=str, default="outputs", help="Directory to save the generated files")
    parser.add_argument("--control_mode", type=str, default="guidance", choices=["none", "spacecontrol", "guidance", "both"])
    parser.add_argument("--guidance_type", type=str, default="containment", choices=["latent", "occupancy", "containment", "shell"])
    parser.add_argument("--steps", type=int, default=12)
    parser.add_argument("--rescale_t", type=float, default=5.0)
    parser.add_argument("--guidance_strength", type=float, default=7.5)
    parser.add_argument("--guidance_interval", type=float, nargs=2, default=[0.6, 1.0])
    parser.add_argument("--guidance_rescale", type=float, default=0.7)
    parser.add_argument("--geometry_guidance_strength", type=float, default=1.0)
    parser.add_argument("--geometry_guidance_interval", type=float, nargs=2, default=[0.5, 0.95])
    parser.add_argument("--geometry_guidance_schedule", type=str, default="constant", choices=["constant", "linear_decay", "linear_rise"])
    parser.add_argument("--geometry_guidance_rescale", type=lambda x: str(x).lower() in {"1", "true", "yes"}, default=True)
    parser.add_argument("--geometry_grad_clip", type=float, default=5.0)
    parser.add_argument("--geometry_guidance_cfg_mode", type=str, default="cond_only", choices=["cond_only", "with_cfg"])
    parser.add_argument("--bce_weight", type=float, default=None)
    parser.add_argument("--dice_weight", type=float, default=None)
    parser.add_argument("--envelope_radius", type=int, default=2)
    parser.add_argument("--interior_weight", type=float, default=0.1)
    parser.add_argument("--contain_weight", type=float, default=2.0)
    parser.add_argument("--outside_weight", type=float, default=2.5)
    parser.add_argument("--shell_weight", type=float, default=0.0)
    parser.add_argument("--bottom_weight", type=float, default=1.0)
    parser.add_argument("--bottom_band_ratio", type=float, default=0.18)
    parser.add_argument("--bottom_outer_margin", type=int, default=1)
    parser.add_argument("--normalize_control", action="store_true", help="Renormalize the control mesh into the unit cube")
    parser.add_argument("--normalize_padding", type=float, default=0.0)
    parser.add_argument("--normalize_padding_x", type=float, default=0.02)
    parser.add_argument("--normalize_padding_y", type=float, default=0.0)
    parser.add_argument("--normalize_padding_z", type=float, default=0.0)
    parser.add_argument("--fill_holes_max_hole_perimeter", type=float, default=0.0)
    parser.add_argument("--solidify_volume", action="store_true")
    parser.add_argument("--solidify_include_control", type=lambda x: str(x).lower() in {"1", "true", "yes"}, default=True)
    parser.add_argument("--solidify_resolution", type=int, default=128)
    parser.add_argument("--solidify_generated_surface_dilation", type=int, default=2)
    parser.add_argument("--solidify_control_surface_dilation", type=int, default=2)
    parser.add_argument("--solidify_closing_iters", type=int, default=2)
    parser.add_argument("--solidify_final_closing_iters", type=int, default=1)
    parser.add_argument("--solidify_smoothing_iters", type=int, default=0)
    parser.add_argument("--make_watertight", action="store_true")
    parser.add_argument("--watertight_max_hole_perimeter", type=float, default=10.0)
    parser.add_argument("--watertight_min_component_area", type=float, default=1e-4)
    main(parser.parse_args())
